CREATE TABLE "departments" (
  "department_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "department_name" varchar(100) UNIQUE
);

CREATE TABLE "students" (
  "student_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50),
  "last_name" varchar(50),
  "email" varchar(100) UNIQUE,
  "date_of_birth" date,
  "department_id" int,
  "user_id" int
);

CREATE TABLE "instructors" (
  "instructor_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(50),
  "last_name" varchar(50),
  "email" varchar(100) UNIQUE,
  "department_id" int,
  "user_id" int
);

CREATE TABLE "courses" (
  "course_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_name" varchar(100),
  "credits" int,
  "department_id" int,
  "instructor_id" int
);

CREATE TABLE "classrooms" (
  "classroom_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "building" varchar(50),
  "room_number" varchar(10),
  "capacity" int
);

CREATE TABLE "schedules" (
  "schedule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int,
  "classroom_id" int,
  "schedule_day" varchar(20),
  "start_time" time,
  "end_time" time
);

CREATE TABLE "exams" (
  "exam_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int,
  "exam_date" date,
  "start_time" time,
  "end_time" time,
  "classroom_id" int,
  "exam_type" varchar(100)
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE,
  "password_hash" varchar(255),
  "email" varchar(100) UNIQUE,
  "created_at" timestamp,
  "role_id" int
);

CREATE TABLE "roles" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar(100) UNIQUE
);

CREATE TABLE "enrollment" (
  "enrollment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "course_id" int,
  "enrolled_at" timestamp
);

CREATE TABLE "participation" (
  "participation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "schedule_id" int,
  "student_id" int,
  "attended" bool,
  "date" date
);

CREATE TABLE "performance" (
  "performance_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "exam_id" int,
  "grade" float
);

ALTER TABLE "students" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("department_id");

ALTER TABLE "instructors" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("department_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("department_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("instructor_id") REFERENCES "instructors" ("instructor_id");

ALTER TABLE "schedules" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("course_id");

ALTER TABLE "schedules" ADD FOREIGN KEY ("classroom_id") REFERENCES "classrooms" ("classroom_id");

ALTER TABLE "exams" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("course_id");

ALTER TABLE "exams" ADD FOREIGN KEY ("classroom_id") REFERENCES "classrooms" ("classroom_id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "enrollment" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("student_id");

ALTER TABLE "enrollment" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("course_id");

ALTER TABLE "participation" ADD FOREIGN KEY ("schedule_id") REFERENCES "schedules" ("schedule_id");

ALTER TABLE "participation" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("student_id");

ALTER TABLE "performance" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("student_id");

ALTER TABLE "performance" ADD FOREIGN KEY ("exam_id") REFERENCES "exams" ("exam_id");

ALTER TABLE "instructors" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "students" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
